services:
  - type: web
    name: accessed-backend
    runtime: python
    rootDir: backend
    buildCommand: apt-get install -y tesseract-ocr && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
